### ISSUE TITLE
Throws with QGIS 3.14

### ISSUE THREAD

**Issue by zakjan** [jawensi/DEMto3D-QGIS-Plugin#25]
```
An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'rasterUnitsPerPixelX' 
Traceback (most recent call last):
  File "/Users/zakjan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DEMto3D/DEMto3D.py", line 116, in run
    demto3d_dlg = DEMto3D_dialog.DEMto3DDialog(self.iface)
  File "/Users/zakjan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DEMto3D/DEMto3D_Dialog/DEMto3D_dialog.py", line 115, in __init__
    self.get_raster_properties()
  File "/Users/zakjan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DEMto3D/DEMto3D_Dialog/DEMto3D_dialog.py", line 375, in get_raster_properties
    self.cell_size = self.layer.rasterUnitsPerPixelX()
AttributeError: 'NoneType' object has no attribute 'rasterUnitsPerPixelX'

Python version: 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)] 
QGIS version: 3.14.0-Pi Pi, 9f7028fd23
```

DEM files used are downloaded from http://srtm.csi.cgiar.org/srtmdata/

**Comment by jawensi** [comment]
I fixed it. Try to reinstall DEMto3D through the Plugin Manager of QGIS.

**Comment by zakjan** [comment]
Thanks!
