### ISSUE TITLE
Error when dragging an extent

### ISSUE THREAD

**Issue by pcav** [jawensi/DEMto3D-QGIS-Plugin#7]
Traceback (most recent call last):
  File "/home/paolo/Scrivania/butta/2_10/python/plugins/DEMto3D/DEMto3D_Dialog/DEMto3D_dialog.py", line 475, in canvasReleaseEvent
    self.callback(r)
  File "/home/paolo/Scrivania/butta/2_10/python/plugins/DEMto3D/DEMto3D_Dialog/DEMto3D_dialog.py", line 226, in get_custom_extent
    self.iface.actionTouch().trigger()
AttributeError: 'NoneType' object has no attribute 'trigger'

**Comment by jawensi** [comment]
Trigger event fixed
